### ISSUE TITLE
Razorpay integration not working as expected in Mobile browser

### ISSUE THREAD

**Issue by AvinashMudunuri** [the-special-character/-tsc-medusa-plugin-razorpay-payment#2]
Thank you for this plugin.

In a normal desktop browser, the total end-to-end flow works perfectly: on submit in the checkout page --> razorpay --> payment success --> redirects to app --> order placed --> redirects to order summary.

In the Mobile browser, the total end-to-end flow : on submit in the checkout page --> razorpay --> payment success --> redirects to callback_url --> and stops. 

Am I missing any config?

![Image](https://github.com/user-attachments/assets/4a05a762-e423-40e9-9063-d18af22bbb62)

**Comment by AvinashMudunuri** [comment]
Fixed the issue

**Comment by Nora-Aurora** [comment]
> Fixed the issue

Could you tell me how to fix this issue?

**Comment by AvinashMudunuri** [comment]
@Nora-Aurora i have updated my razorPay options and mobile specific improvements, added comments as well in the below code

<img width="1772" height="3066" alt="Image" src="https://github.com/user-attachments/assets/d3fbe456-6893-4a8e-9469-7cf66c97080e" />

**Comment by rounnakk** [comment]
Thanks! @AvinashMudunuri 

Appreciate it

**Comment by shubhankartrivedi** [comment]
I'm getting this issue but still can't understand how @AvinashMudunuri fixed it through the code he is showing.
If anyone could help, i'll be glad
